on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
        with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USER1 }}
                  password: ${{ secrets.FTP_PASSWORD }}
# To deploy to ACA HELP LINE server, just change FTP_USER to FTP_USER1

# FTP_USER = NCA LEaderboard
# FTP_USER1 = ACA HelpLine
